/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/order-summary`; params?: Router.UnknownInputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CartPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../context/MenuContext`; params?: Router.UnknownInputParams; } | { pathname: `/admin/index`; params?: Router.UnknownInputParams; } | { pathname: `/admin/edit`; params?: Router.UnknownInputParams; } | { pathname: `/menu-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin/index` | `/admin/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin/edit` | `/admin/edit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/order-summary`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CartPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/MenuContext`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/index`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/menu-detail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin/index` | `/admin/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin/edit` | `/admin/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/order-summary${`?${string}` | `#${string}` | ''}` | `/../context/CartContext${`?${string}` | `#${string}` | ''}` | `/../constants/layout${`?${string}` | `#${string}` | ''}` | `/../components/CartPanel${`?${string}` | `#${string}` | ''}` | `/../context/MenuContext${`?${string}` | `#${string}` | ''}` | `/admin/index${`?${string}` | `#${string}` | ''}` | `/admin/edit${`?${string}` | `#${string}` | ''}` | `/menu-detail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin/index${`?${string}` | `#${string}` | ''}` | `/admin/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin/edit${`?${string}` | `#${string}` | ''}` | `/admin/edit${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/order-summary`; params?: Router.UnknownInputParams; } | { pathname: `/../context/CartContext`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/layout`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CartPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../context/MenuContext`; params?: Router.UnknownInputParams; } | { pathname: `/admin/index`; params?: Router.UnknownInputParams; } | { pathname: `/admin/edit`; params?: Router.UnknownInputParams; } | { pathname: `/menu-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin/index` | `/admin/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin/edit` | `/admin/edit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; };
    }
  }
}
